netaddiction_theme_rewrite/static/src/css/category.css, netaddiction_theme_rewrite/static/src/css/global.css, netaddiction_theme_rewrite/static/src/css/home.css, netaddiction_theme_rewrite/static/src/css/product.css, netaddiction_theme_rewrite/templates/assets.xml, netaddiction_theme_rewrite/templates/google-snippet/product.xml, netaddiction_theme_rewrite/templates/template_product.xml
ho fatto qualche modifica per i css delle category + fixato un errore nei google rich snippet
=> css category + fix google snippets

.gitmodules, netaddiction_payments/__manifest__.py, netaddiction_payments/models/sale_order.py, netaddiction_payments/views/sale_order.xml, netaddiction_warehouse/__manifest__.py
Dipende dalla: saydigital/ecommerce#2
=> Delay payment deps

netaddiction_warehouse/__manifest__.py, netaddiction_warehouse/static/src/js/supplier_load.js
Here a very simple query to check data from interface to database
```
SELECT
pt.name,
sum(sm.product_uom_qty)
FROM
stock_move as sm, product_product as pp, product_template as pt
WHERE
sm.picking_id IN {{PICKING_IDS_FROM_PICKING_BATCH}}
AND sm.product_id = pp.id
AND pp.product_tmpl_id = pt.id
GROUP BY
pt.name
```
=> [FIX][netaddiction_warehouse] Supplier load products quantities

netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py, netaddiction_theme_rewrite/templates/custom_product_label.xml, netaddiction_website_stock_notify/views/website_template.xml, theme_clarico_vega/templates/netaddiction_customization.xml
fixati problemi con i permessi
=> 14.0 netaddiction custom

odoo_website_wallet/README, odoo_website_wallet/__manifest__.py, odoo_website_wallet/controllers/main.py
This PR breaks changes done by Fabio on website_all_in_one. Don't merge it until Fabio acks the PR itself
=> 14.0 xxxx indian updates

netaddiction_theme_rewrite/__manifest__.py, netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py, netaddiction_theme_rewrite/static/src/css/cart_payment.css, netaddiction_theme_rewrite/static/src/css/user_orders.css, netaddiction_theme_rewrite/static/src/js/check_limit.js, netaddiction_theme_rewrite/templates/assets.xml, netaddiction_theme_rewrite/templates/template_checkout.xml, netaddiction_theme_rewrite/templates/template_orders.xml
modifiche meta description e title + limiti di vendita funzionanti + modifiche ordini + tooltip stripe + noindex su b2b + rimozione scelta quantità su cart line di tipo service
=> immagini dentro gli ordini

advance_website_all_in_one/controllers/main.py, scripts/duplicates_attribute.json
Merge of a single RC PR already approved under the freeze policy
=> Go Live #2

netaddiction_theme_rewrite/__manifest__.py, netaddiction_theme_rewrite/static/src/css/global.css, netaddiction_theme_rewrite/static/src/css/home.css, netaddiction_theme_rewrite/static/src/css/product.css, netaddiction_theme_rewrite/templates/assets.xml, netaddiction_theme_rewrite/templates/template_category.xml, netaddiction_theme_rewrite/templates/template_checkout.xml, netaddiction_theme_rewrite/templates/template_product.xml, netaddiction_theme_rewrite/templates/template_wallet.xml, netaddiction_website/__manifest__.py, netaddiction_website/controllers/main.py, netaddiction_website/views/web/homepage.xml, netaddiction_website/views/web/old_home.xml, theme_clarico_vega/__manifest__.py, theme_clarico_vega/templates/netaddiction_customization.xml
Inserita nuova home + rivisitate le categorie dentro il menu laterale + nascoste immagini di categoria da pagina 2 in poi + aggiunto un falso bottone per accettazione privacy in registrazione (diventerà vero prima o poi) + css vari e modifiche seo
=> aggiunta nuova home + rimosso wallet + fix menu laterale + fix vari css

netaddiction_warehouse/models/stock_picking.py
=> [FIX][netaddiction_warehouse] Fix account.move field name

netaddiction_products/__manifest__.py, netaddiction_products/models/product.py, netaddiction_products/views/product_views.xml
Non mergiare fino a completamento dei dovuto test
=> [IMP][netaddiction_products] Show supplier info filtered for products

.gitmodules
Reverts saydigital/netaddiction_addons#221
=> Revert "[ADD][odoo_business_relationships] Add submodules"

netaddiction_theme_rewrite/__manifest__.py, netaddiction_theme_rewrite/static/src/css/global.css, netaddiction_theme_rewrite/static/src/css/product.css, theme_clarico_vega/__manifest__.py, theme_clarico_vega/templates/netaddiction_customization.xml
wrappata una lable con un if ch creafa errore su wishlist
=> 14.0 fix wishlist

theme_clarico_vega/__manifest__.py, theme_clarico_vega/static/src/js/frontend/ajax_cart.js
so che non vanno lasciati commenti ma questo è il codice di clarico quindi vorrei evitare di cestinarlo
=> fix scroll

netaddiction_warehouse/models/netaddiction_manifest.py
Risolve l'errore dello screenshot
=> [FIX][netaddiction_warehouse] Float convertion error in manifest check

netaddiction_payments/__manifest__.py, netaddiction_payments/models/stripe.py, netaddiction_website/__manifest__.py, netaddiction_website/views/web/product.xml
Oltre al fix per Facebook ho aggiunto un banalissimo controllo per Stripe, sono consapevole che dovrei farlo qui ma aprire un branch a parte e farlo li, perdonatemi :)
=> Fix stripe duplicate payment + fix Facebook pixel click events

netaddiction_special_offers/__manifest__.py, netaddiction_special_offers/controller/main.py, netaddiction_special_offers/templates/template_offers.xml, netaddiction_special_offers/templates/template_promotion.xml, netaddiction_theme_rewrite/__manifest__.py, netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py, netaddiction_theme_rewrite/static/src/css/category.css, netaddiction_theme_rewrite/static/src/css/global.css, netaddiction_theme_rewrite/templates/filters.xml, netaddiction_theme_rewrite/templates/template_category.xml, netaddiction_theme_rewrite/templates/template_checkout.xml, netaddiction_theme_rewrite/templates/template_product.xml, netaddiction_theme_rewrite/templates/template_tag.xml, theme_clarico_vega/__manifest__.py, theme_clarico_vega/templates/netaddiction_customization.xml
filtri per tag e prezzi nelle pagine custom + messaggio nel carrello da sloggato
=> filtri per tag e prezzi nelle pagine custom

netaddiction_account/__init__.py, netaddiction_account/__manifest__.py, netaddiction_account/models/account.py, netaddiction_account/security/ir.model.access.csv, netaddiction_account/wizard/__init__.py, netaddiction_account/wizard/check_csv_cod.py, netaddiction_account/wizard/check_csv_cod.xml
Aggiunta funzionalità per l'amministrazione per verificare i contrassegni
=> Netaddiction account check cod

netaddiction_website/__manifest__.py, netaddiction_website/models/__init__.py, netaddiction_website/models/facebook.py
Override della search dei prodotti dal modello product.template a product.product
=> Search domain: product.template -> product.product

netaddiction_special_offers/__manifest__.py, netaddiction_special_offers/templates/product_item.xml, netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py, netaddiction_theme_rewrite/static/src/css/product.css, netaddiction_theme_rewrite/static/src/js/custom_button_buy.js, netaddiction_theme_rewrite/templates/template_checkout.xml
mostrava le immagini dei padri ora è corretto
=> fixate immagini prodotti

netaddiction_special_offers/__manifest__.py, netaddiction_special_offers/templates/template_offers.xml, netaddiction_theme_rewrite/__manifest__.py, netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py, netaddiction_theme_rewrite/static/src/css/global.css, netaddiction_theme_rewrite/static/src/js/popup_add_to_cart_custom.js
risolto problema animazione label su ios
=> fix label spedizione gratuita da ios

netaddiction_warehouse/models/product_product.py, netaddiction_warehouse/static/src/js/inventory_reports.js, session_redis/README.rst, session_redis/__init__.py, session_redis/__manifest__.py, session_redis/http.py, session_redis/json_encoding.py, session_redis/session.py
Instructions for the deploy:
1) Copy this configuration inside the odoo.service unit file:
Environment="ODOO_SESSION_REDIS=1"
Environment="ODOO_SESSION_REDIS_HOST=<valore>"
Environment="ODOO_SESSION_REDIS_PORT=6379"
Environment="ODOO_SESSION_REDIS_PASSWORD=<valore>"
Environment="ODOO_SESSION_REDIS_EXPIRATION=15552000"
Environment="ODOO_SESSION_REDIS_EXPIRATION_ANONYMOUS=21600"
2) Add this entry to the Odoo configuration file:
server_wide_modules=web,session_redis
3) Installare `redis` via pip con l'utente odoo_vin (in prod)
4) Riavviare Odoo
5) Installare session_redis
=> Sessions on redis

netaddiction_theme_rewrite/__manifest__.py, netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py, netaddiction_theme_rewrite/templates/assets.xml, netaddiction_theme_rewrite/templates/template_checkout.xml, theme_clarico_vega/__manifest__.py, theme_clarico_vega/static/src/js/frontend/ajax_cart.js
so che l'id non vanno messi in quel modo, ma è inevitabile dato che vogliono mappare solo determinate categorie
=> inserito google tag per categorie lego

netaddiction_website/__manifest__.py, netaddiction_website/controllers/main.py, netaddiction_website/views/web/harry_potter_shop.xml
blank page di harrypotter da customizzare con il tema clarico
=> creata pagina shop harry potter

netaddiction_theme_rewrite/__manifest__.py, netaddiction_theme_rewrite/static/src/css/global.css, netaddiction_theme_rewrite/static/src/js/custom_button_buy.js, netaddiction_theme_rewrite/static/src/xml/template_label.xml, netaddiction_website_stock_notify/__manifest__.py, theme_clarico_vega/__manifest__.py, theme_clarico_vega/templates/netaddiction_customization.xml, theme_clarico_vega/templates/product.xml
=> 14.0 fix frontend

netaddiction_theme_rewrite/__manifest__.py, netaddiction_theme_rewrite/templates/assets.xml, theme_clarico_vega/__manifest__.py, theme_clarico_vega/static/src/js/frontend/ajax_cart.js
spostato evento conversione LEGO gtag e test gestione gtag multiplo
=> spostato evento conversione e diviso init gtag
